"""Generate every thesis figure from MLflow artifacts - deterministically.

THE RULE: every figure in your thesis is produced by a function in this
file. No hand-made screenshots, no notebook one-offs. If a figure cannot
be regenerated by ``uv run python scripts/make_figures.py``, it does not
go into the thesis. This is checked at submission (tests/test_submission.py).

Inputs allowed: the MLflow run of your registered model (metrics, params,
artifacts) and the datasets under $DATA_DIR. Nothing else - no local
files outside the repo, no manual preprocessing.

Usage:
    uv run python scripts/make_figures.py                  # latest registered model
    uv run python scripts/make_figures.py --run_id <id>    # specific run
    uv run python scripts/make_figures.py --output figures/

Add a figure: write a ``fig_<name>(ctx)`` function, register it in FIGURES.
Each function receives a FigureContext and saves into ``ctx.output_dir``.
"""

import argparse
import logging
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # repo root

import matplotlib  # noqa: E402

matplotlib.use("Agg")  # headless server / container - before pyplot import
import matplotlib.pyplot as plt  # noqa: E402
import mlflow  # noqa: E402
from mlflow.tracking import MlflowClient  # noqa: E402

from src.visualization.config import setup_plot_for_thesis  # noqa: E402

logger = logging.getLogger(__name__)

TRACKING_URI = "sqlite:///./mlruns/mlflow.db"


@dataclass
class FigureContext:
    """Everything a figure function may read from."""

    client: MlflowClient
    run_id: str
    output_dir: Path

    def save(self, fig, name: str) -> None:
        """Save a figure as PDF (for LaTeX) and PNG (for quick viewing)."""
        for ext in ("pdf", "png"):
            path = self.output_dir / f"{name}.{ext}"
            fig.savefig(path, bbox_inches="tight", dpi=300)
        plt.close(fig)
        logger.info(f"wrote {self.output_dir / name}.pdf/.png")


# ---------------------------------------------------------------------------
# Figure functions - one per thesis figure. ADD YOURS BELOW.
# ---------------------------------------------------------------------------


def fig_loss_curves(ctx: FigureContext) -> None:
    """Training and validation loss over epochs (works for every run)."""
    fig, ax = plt.subplots()
    for metric, label in [("train/loss", "train"), ("val/loss", "validation")]:
        history = ctx.client.get_metric_history(ctx.run_id, metric)
        if not history:
            logger.warning(f"metric '{metric}' not found in run {ctx.run_id}")
            continue
        history.sort(key=lambda m: m.step)
        ax.plot([m.step for m in history], [m.value for m in history], label=label)
    ax.set_xlabel("Step")
    ax.set_ylabel("Loss")
    ax.legend()
    ctx.save(fig, "loss_curves")


# def fig_prediction_example(ctx: FigureContext) -> None:
#     """TEMPLATE: model prediction vs ground truth on one test sample.
#
#     Pattern: load the registered model, pull one sample from the test
#     dataloader, predict, and plot with src.visualization helpers.
#     """
#     import torch
#     from omegaconf import OmegaConf
#     from src.data import get_datamodule
#     from src.utils.config_manager import ConfigManager
#     from src.visualization.pointcloud import plot_pointclouds
#
#     model = mlflow.pytorch.load_model(f"runs:/{ctx.run_id}/model")
#     model.eval()
#     config_path = ctx.client.download_artifacts(ctx.run_id, "config.yaml")
#     config = ConfigManager.from_yaml(config_path)
#     cfg = OmegaConf.create(
#         {"dataset": config.dataset_config, "training": config.training_config}
#     )
#     datamodule = get_datamodule(cfg)
#     datamodule.setup(stage="test")
#     batch = next(iter(datamodule.test_dataloader()))
#     with torch.no_grad():
#         prediction = model(batch)
#     fig = plot_pointclouds(...)  # your visualization here
#     ctx.save(fig, "prediction_example")


#: Register every thesis figure here: {figure_name: function}.
FIGURES = {
    "loss_curves": fig_loss_curves,
    # "prediction_example": fig_prediction_example,
}


# ---------------------------------------------------------------------------


def latest_registered_run_id(client: MlflowClient) -> str:
    """Run id behind the newest registered model version (any name)."""
    versions = client.search_model_versions()
    if not versions:
        raise SystemExit(
            "No registered model found. Register your best run first:\n"
            "  uv run evaluate.py --run_id <id> --datasets all --register"
        )
    latest = max(versions, key=lambda v: int(v.version))
    return latest.run_id


def main() -> None:
    """Generate all registered figures."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run_id", help="MLflow run id (default: latest registered)")
    parser.add_argument("--output", default="figures", help="Output directory")
    parser.add_argument("--only", nargs="*", help="Generate only these figures")
    args = parser.parse_args()

    mlflow.set_tracking_uri(TRACKING_URI)
    client = MlflowClient()
    run_id = args.run_id or latest_registered_run_id(client)

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    setup_plot_for_thesis()

    ctx = FigureContext(client=client, run_id=run_id, output_dir=output_dir)
    names = args.only or list(FIGURES)
    for name in names:
        logger.info(f"generating '{name}' from run {run_id}")
        FIGURES[name](ctx)

    logger.info(f"done: {len(names)} figure(s) in {output_dir}/")


if __name__ == "__main__":
    main()
